### ISSUE TITLE
No truncator rendered if first list item is hidden

### ISSUE THREAD

**Issue by carolinmaisenbacher** [maladr0it/react-truncate-list#20]
First and foremost: thanks for the great library!

I am using the truncated list inside a table. On smaller screen sizes it sometimes happens that not even the first list item fully fits into the outside container. In that case, I expected the list to then only render the truncator. 

However in reality, no truncator is being rendered and also no list item, which means the cell is left blank.

Here is a codesandbox to visualize my issue:
https://codesandbox.io/s/react-truncate-list-demo-yody68?file=/src/App.tsx

**Comment by maladr0it** [comment]
Thank you for your feedback!  I'll find some time to address this issue this weekend :)

**Comment by carolinmaisenbacher** [comment]
That would be amazing! Thank you very much for maintaining this awesome library :)

**Comment by JulianWielga** [comment]
I did a PR with the fix, and until the new version release it looks like it is enough to add one empty invisible element at the beginning of the list to show truncator for "all" elements.

**Comment by maladr0it** [comment]
@carolinmaisenbacher in case you missed all of this, please use an empty invisible element to cover your use-case. I will consider supporting your use-case in the future but as of now it adds a little too much complexity to the code, which I'm in the process of improving.
