### ISSUE TITLE
License

### ISSUE THREAD

**Issue by parkm** [maladr0it/react-truncate-list#22]
Hey just wondering if you had any plans on adding a license to this repo?

**Comment by parkm** [comment]
Oh so it looks like there is a license set on NPM, but no license file in the repo itself
https://www.npmjs.com/package/react-truncate-list

It's ISC, so that would be
> Copyright \<YEAR> \<OWNER>
> 
> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
> 
> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

**Comment by maladr0it** [comment]
Resolved, thanks for that :)

https://github.com/maladr0it/react-truncate-list/pull/28
