### ISSUE TITLE
No children error: Cannot set property 'hidden' of undefined

### ISSUE THREAD

**Issue by denchen** [maladr0it/react-truncate-list#3]
First off, great library!

If `alwaysShowTruncator` is set, and children is empty, then the library will crash with:

```
index.js:27 TypeError: Cannot set property 'hidden' of undefined
    at truncate (index.js:73)
```

Example:

```javascript
<TruncatedList
  className="list"
  alwaysShowTruncator
  renderTruncator={({ hiddenItemsCount }) => hiddenItemsCount}
>
</TruncatedList>
```

I ran into this problem because in my component, the list to render within `<TruncatedList>` may not be always available on first render. The list is created within a `useEffect()`, so it comes in on second render. My current workaround is to insert an empty `<div/>` if my list is not available. The other thing I could do is not render `<TruncatedList>` at all if the list isn't available.

**Comment by maladr0it** [comment]
Thanks very much for your early feedback.  I have pushed a new version (0.2.0) that may address this issue.  The new behavior of `alwaysShowTruncator` is to not show the truncator if the list is empty, but otherwise always show it.

Your thoughts on this change would be appreciated.

**Comment by maladr0it** [comment]
As for not rendering the list at all, I would recommend conditional rendering like so:
```jsx
{items.length && (
  <TruncatedList ...etc />
)}
```

**Comment by denchen** [comment]
The fix worked. I no longer need any of the workarounds.
