### ISSUE TITLE
Add support for CJS

### ISSUE THREAD

**Issue by MrLeebo** [maladr0it/react-truncate-list#32]
Hi Mal! 👋 

react-truncate-list publishes its package using ESM modules. Would you consider adding dual-support for both ESM and CJS? 

When using jest configured with `testEnvironment: 'jsdom'`, jest has trouble importing ESM modules in spec files, causing it to fail to parse components that import react-truncate-list in unit tests.

As a workaround, you can configure jest to transform the react-truncate-list code but I think it would be better if the package produced both output styles.

Workaround:

```diff
// jest.config.js
{
  testEnvironment: "jsdom",
  transform: {
    "^.+\\.tsx?$": ["ts-jest", { isolatedModules: true }],
    "^.+\\.jsx?$": "babel-jest"
  },
-  transformIgnorePatterns: ["/node_modules/", ".scss"]
+  transformIgnorePatterns: ["/node_modules/(?!(react-truncate-list)/)", ".scss"]
}
```

**Comment by maladr0it** [comment]
Hiya, I added a dist/cjs directory and marked it in package.json. Let me know if that helped, it's my first time publishing for CJS.

**Comment by MrLeebo** [comment]
That did the trick, all my jest tests pass and no jest config hack needed 👍
