### ISSUE TITLE
The `renderTruncator` seems to have an incorrect number of "additionalCount" passed to it

### ISSUE THREAD

**Issue by jasikpark** [maladr0it/react-truncate-list#33]
I'm using this wonderful library to implement a truncating tags design that also has the individual tags truncating. The problem that I'm running into atm is that the count of hidden tags will be incorrect, so my `+N` pill will be wrong, plus the tooltip that shows the rest of the tags will be incomplete

Hopefully I can create a reproduction of this bug for you / sort out what's going wrong...

**Comment by maladr0it** [comment]
Hi, thanks for your feedback. Yes, could you please make reproduction of the problem? Preferably with codesandbox.io

**Comment by jasikpark** [comment]
Here, I think I have an effective repro: https://codesandbox.io/p/sandbox/trusting-bhaskara-wk2wrm?file=%2Fpackage.json%3A1%2C1

There are 15 list items, but only the last one is in the list..

**Comment by maladr0it** [comment]
I think you made a mistake here:

const extraTags = tags.slice(hiddenItemsCount - 1);

if this is meant to represent the tags that aren't visible, you should actually do:

const extraTags = tags.slice(tags.length - hiddenItemsCount);

Let me know if this works :)

**Comment by jasikpark** [comment]
🙈

**Comment by jasikpark** [comment]
thx!

**Comment by jasikpark** [comment]
<img width="293" alt="image" src="https://github.com/maladr0it/react-truncate-list/assets/10626596/a822004c-dd09-46ad-9d1e-d2e8ae611851">
success!

<img width="1089" alt="image" src="https://github.com/maladr0it/react-truncate-list/assets/10626596/9387ba7b-bda6-4556-81d9-5b98706b6191">

<img width="385" alt="image" src="https://github.com/maladr0it/react-truncate-list/assets/10626596/1c2ffa3e-b629-4808-9516-bd5c512b7373">

lol was struggling on how to make the individual pills truncate when they were too large for the container, but fixed it w/ :


```css
:global(.react-truncate-list li) {
  max-width: 100%;
}
```

**Comment by maladr0it** [comment]
Hey, I agree that based on your design it does seem this is probably better addressed with flexbox and text-overflow: ellipsis, rather than this library.

I am curious though, were you having performance trouble with this library? I have some ideas to improve the performance but it would help to know what situation was causing the issue and how bad it was.

Thanks so much for your feedback :)

**Comment by jasikpark** [comment]
Yeah, so I may revisit this later; + the reason i was making the claim was that we use storybook-test to test our lists and some of our tests were timing out

**Comment by jasikpark** [comment]
I think I may need to revisit the algorithm in this, since I want to show a single tag at full width, but truncated, before I show any of the other 15? 

It seems like the current setup tries to pack as many in as possible; tried `min(fit-content, 100%)` or something, but that wasn't effective it seems..
